apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: whisper-models
  name: whisper-models
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
